In [ ]:
#language translator: if word isn't in dictionary, let user know. Define dictionary, define code to use it, no function required. 

# Programming Assignment 5
---
**Author:** William Muckler  
**Version:** 1.0  
**Semester:** Spring 2024 

This *notebook* contains my solution(s) to **Programming Assignment 5**


### Problem 1- Language Translator

In [15]:
translationEtoS = {
    'yes': 'si',
    'no': 'no',
    'me': 'me',
    'he': 'el',
    'she': 'ella',
    'you': 'tu',
    'year': 'ano',
    'country': 'pais',
    'time': 'tiempo',
    'part': 'parte',
    'life': 'vida',
    'occasion': 'vez',
    'day': 'dia',
    'new': 'nueva',
    'big': 'grande',
    'good': 'bueno',
    'last': 'ultimo',
    'greater': 'mayor',
    'national': 'nacional',
    'better': 'mejor',
}

while True:
    word = input("Enter a word to translate from English to Spanish: ")
    if word == 'Q':
        break
    elif word.lower() in translationEtoS:
        translation = translation_dict[word.lower()]
        print(f"The Spanish word for {word} is {translation}.")
    else:
        print(f"The Spanish word for {word} is not in this dictionary.")

Enter a word to translate from English to Spanish:  yes


The Spanish word for yes is si.


Enter a word to translate from English to Spanish:  Q


### Problem 2- Translating Morse Code

In [18]:
morse_code_dict = {
    'A': '.-', 
    'B': '-...', 
    'C': '-.-.', 
    'D': '-..', 
    'E': '.', 
    'F': '..-.', 
    'G': '--.', 
    'H': '....', 
    'I': '..', 
    'J': '.---',
    'K': '-.-', 
    'L': '.-..', 
    'M': '--', 
    'N': '-.', 
    'O': '---', 
    'P': '.--.', 
    'Q': '--.-', 
    'R': '.-.', 
    'S': '...', 
    'T': '-',
    'U': '..-', 
    'V': '...-', 
    'W': '.--', 
    'X': '-..-', 
    'Y': '-.--', 
    'Z': '--..',
    '0': '-----', 
    '1': '.----', 
    '2': '..---', 
    '3': '...--', 
    '4': '....-', 
    '5': '.....',
    '6': '-....', 
    '7': '--...', 
    '8': '---..', 
    '9': '----.'
}

In [29]:

def morse_translate(sentence):
    morse_code_sentence = ""
    for english in sentence.upper():
        if english in morse_code_dict:
            morse_code_sentence += morse_code_dict[char] + " "
while True:
    message = input("Enter a message: ")
    if message.lower() == 'q':
        print("Done.")
        break
    morse_code = translate_to_morse(message)
    print("English to Morse Code:", morse_code)

Enter a message:  dd


English to Morse Code: -.. -..


Enter a message:  q


Done.


### Problem 3- Comparing Majors/Minors

In [37]:
computer_science_minor = {'CS130', 'CS131', 'CS215'}
business_administration_minor = {'BUSA103', 'BUSA203', 'BUSA301','BUSA305'}
business_analytics_minor = {'BUSA103', 'BUSA245', 'BUSA346','CS150','DS160','DS300'}
data_science_major = {'BUSA103', 'BUSA245', 'BUSA346','CS150','DS160','DS300','DS450','MATH205','MATH215','MATH430','ECON410'}

In [38]:
ba_ba = business_administration_minor.intersection(business_analytics_minor)
print("Courses overlapping between Business Administration and Business Analytics minors:", ba_ba)

cs_ba = computer_science_minor.union(business_administration_minor)
print("All courses for a student minoring in Business Administration and Computer Science:", cs_ba)

ba_ba = business_administration_minor.difference(business_analytics_minor)
print("Courses in Business Administration minor but not in Business Analytics minor:", ba_ba)

overlap = computer_science_minor.intersection(data_science_major)
print("Overlap between Computer Science major and Data Science major:", overlap)

ba_ds = business_analytics_minor.issubset(data_science_major)
print("Business Analytics minor subsumed by Data Science major:", ba_ds)

Courses overlapping between Business Administration and Business Analytics minors: {'BUSA103'}
All courses for a student minoring in Business Administration and Computer Science: {'BUSA301', 'BUSA203', 'BUSA305', 'CS131', 'CS215', 'BUSA103', 'CS130'}
Courses in Business Administration minor but not in Business Analytics minor: {'BUSA301', 'BUSA305', 'BUSA203'}
Overlap between Computer Science major and Data Science major: set()
Business Analytics minor subsumed by Data Science major: True


### Problem 4- Working with NumPy

In [48]:
import numpy as np
import random

In [50]:
x = np.random.randint(0, 21, size=(5, 5))
y = np.random.randint(0, 21, size=(5, 5))

matrix_product = np.matmul(array1, array2)
dot_product = np.dot(array1.flatten(), array2.flatten())
print(matrix_product)
print(dot_product)

determinantx = np.linalg.det(array1)
inversex = np.linalg.inv(array1)
determinanty = np.linalg.det(array2)
inversey = np.linalg.inv(array2)
print(det_array1)
print(inversex)
print(determinanty)
print(inversey)

arraya = np.linspace(0, 1, 20)
arrayz = np.linspace(1, 2, 20)
arrayaz = np.concatenate((arraya, arrayz))
reshape = np.reshape(arrayaz, (10, 4))
print(combined_array)
print(reshaped_array)


[[ 253  139  197  122  209]
 [ 275  454  287  378  242]
 [ 297  573  325  394  272]
 [ 351  686  363  470  338]
 [ 372 1030  475  809  366]]
1744
-31833.00000000001
[[ 0.40589954 -0.6385826   0.00097383 -0.14261929  0.34055854]
 [ 0.42531335 -0.67609085  0.10109006 -0.12738353  0.28765746]
 [-0.31731222  0.5256809   0.01897402  0.02767568 -0.20331103]
 [ 0.04127792  0.03675431  0.00574875 -0.00320422 -0.0218641 ]
 [-0.51371219  0.72066723 -0.11035718  0.29101875 -0.36716615]]
34091.999999999935
[[-0.01267159 -0.19324182 -0.01627948  0.27252728  0.27833509]
 [-0.05667019  0.05244632  0.00821307 -0.04740115  0.07579491]
 [-0.18409011  0.27595917  0.18247683 -0.27458055 -0.28742814]
 [ 0.13833157 -0.14044351 -0.02367124  0.11518831  0.01011968]
 [ 0.16015488  0.02569518 -0.13915288 -0.02546052 -0.11275373]]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.842

In [43]:
print(x)
print(y)

[[ 0  9 20 16  9]
 [ 7 11  1 19  0]
 [11  7  6 13 14]
 [12 12  0 11  6]
 [12  5 13  3  5]]
[[14  1 17 13  6]
 [ 4 16 15 15  9]
 [ 7 13 11 12  4]
 [11 15 19  1  1]
 [ 9 10 11  7 19]]
